# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d33244d599e58a97a7b638b74637260ef401d584c1947a351a79ea39634e22eb2613edf36d683797cc04fc0e21e4d13413d3f98e89ea67d8fd93ea0a2090a5c

test:
  secret_key_base: d9938972ae417f538d38e6909d29389b049c74ec00f2ef160e808270a9724fc2999522afccc5dd5927353f12da6e7d25c36ac66f12bcd29f19a5f50244f9c044

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
